apiVersion: apps/v1
kind: Deployment
metadata:
  name: snoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snoring
  template:
    metadata:
      labels:
        app: snoring
    spec:
      containers:
      - name: snoring
        image: "bishnupoudel/serving:v1"
        imagePullPolicy: IfNotPresent

