apiVersion: v1
kind: Service
metadata: 
  name: snoring
spec:
  type: ClusterIP
  ports:
  - port: 8500
    protocol: TCP
    name: snoring-grpc
  - port: 8501
    protocol: TCP
    name: snoring-http
  selector:
    app: snoring